risky: false
version: 8.0
preset: laravel
tab-width: 4
use-tabs: false

#enabled:
#  - strict

disabled:
  - no_unused_imports
finder:
  exclude:
    - "tests"
  name:
    - "*.php"
  not-name:
    - "*Stub.php"
    - index.php
    - server.php
  contains:
    - "Foo"
  not-contains:
    - "config"
  path:
    - "foo/Stuff"
  not-path:
    - "libraries"
  depth:
    - "< 3"